# -*- coding: utf-8 -*-
"""house1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AQGs-GSiKfA0M6tV6HsHdS3W80PTvbDm
"""

import zipfile

with zipfile.ZipFile('/content/house-prices-advanced-regression-techniques (2).zip', 'r') as zip_ref:
    zip_ref.extractall('house_data')

print("Extracted Successfully!")

import os

print(os.listdir('house_data'))

import os
print(os.listdir("house_data"))

!unzip -o "/content/house_data/house-prices-advanced-regression-techniques.zip" -d house_data

import pandas as pd

df = pd.read_csv("house_data/train.csv")

print(df.shape)
df.head()

import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load Dataset
df = pd.read_csv("house_data/train.csv")

# Features
X = df[['GrLivArea', 'BedroomAbvGr', 'FullBath']]

# Target
y = df['SalePrice']

# Split Data
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Train Model
model = LinearRegression()
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluation
print("MAE :", mean_absolute_error(y_test, y_pred))
print("MSE :", mean_squared_error(y_test, y_pred))
print("R2 Score :", r2_score(y_test, y_pred))

# Plot
plt.figure(figsize=(8,6))
plt.scatter(y_test, y_pred)
plt.xlabel("Actual Price")
plt.ylabel("Predicted Price")
plt.title("Actual vs Predicted House Prices")
plt.show()